system/trello_project/apps/trello/urls.py
from django.urls import path

from . import views

app_name = 'trello'
urlpatterns = [
    path('', views.index, name='index'),
    path('create_board', views.create_board, name='create_board')



]

system/trello_project/trello_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.trello.urls'))
]

system/trello_project/apps/trello/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser


class MyUser(AbstractBaseUser):
    name = models.CharField(max_length=40, unique=True)
    email = models.EmailField()
    USERNAME_FIELD = 'name'
    

class BaseModel(models.Model):
    title = models.CharField(max_length=200)

    class Meta:
        abstract = True

class Board(BaseModel):
    users = models.ManyToManyField(MyUser)

    def __str__(self):
        return self.title

class Column(BaseModel):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Card(BaseModel):
    column = models.ForeignKey(Column, on_delete=models.CASCADE)
    date_created = models.DateField()

    def __str__(self):
        return self.title

class Tag(BaseModel):
    card = models.ManyToManyField(Card)

    def __str__(self):
        return self.title

class Task(BaseModel):
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    task_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

system/trello_project/apps/trello/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models import Board

# Create your views here.

def index(request):
    template = 'trello/index.html'
    boards_list = Board.objects.all()

    context = {
        'boards_list': boards_list
    }
    return render(request,  template, context)

def create_board(request):
    template = 'trello/create_board.html'
    return render(request, template)

system/trello_project/apps/trello/templates/trello/create_board.html
<h1>ORA ORA ORA ORA</h1>

<form action="{% url 'trello:create_board' %}">
    Board Title: <br>
    <input type='text' name='board_title' autofocus>
    <input type='submit' value='Create Board'>

system/trello_project/apps/trello/templates/trello/index.html
<h1>Welcome</h1>

<p>Your boards:</p>

<ul>
    {% for board in boards_list %}
        <li>{{ board.title }}</li>
    {% endfor %}
</ul>

<p><a href="{% url 'trello:create_board' %}">New Board</a></p>